name: Code Scan with Bandit

on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        id: bandit_scan
        run: bandit -r . -f json -o bandit_output.json || echo "Bandit scan completed"

      - name: Analyze Bandit Results
        id: analyze_results
        run: |
          critical_issues=$(jq '.results[] | select(.issue_severity=="CRITICAL")' bandit_output.json)
          if [ -n "$critical_issues" ]; then
            echo "Found critical vulnerabilities"
            echo "action=block" >> $GITHUB_ENV
          else
            echo "action=merge" >> $GITHUB_ENV
          fi
        env:
          GITHUB_ENV: ${{ github.env }}

      - name: Comment on Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const action = process.env.action;
            const message = action === "block" ? "Block" : "Successful";
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            });

      - name: Block or Merge Pull Request
        if: env.action == 'block'
        run: exit 1
        env:
          GITHUB_ENV: ${{ github.env }}
